name: ETL Pipeline

on:
  push:
    branches:
      - main

jobs:
  test-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unit tests
      run: pytest tests/
      env:
        PYTHONPATH: ${{ github.workspace }}

    - name: Run ETL
      run: python run_etl.py
      env:
        REPO_URL: ${{ secrets.REPO_URL }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        LOCAL_PATH: repo
        DB_URL: sqlite:///etl_data.db
        TABLE_NAME: etl_table
        PYTHONPATH: ${{ github.workspace }}
